version: '3'

services:
  php:
    build:
      context: .
    ports:
      - 9000:9000
    volumes:
      - ./:/srv/www/taskmanager
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
