version: '3'

services:
  php:
    env_file: .env
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - ./public:/srv/www/taskmanager
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nginx:
    env_file: .env
    image: nginx:1.17.9-alpine
    ports:
      - 8080:80
    volumes:
      - ./public:/srv/www/taskmanager
      - ./docker/server/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    env_file: .env
    image: mysql:5.7
    ports:
      - 3306:3306
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
